apiVersion: v1
kind: Service
metadata:
  name: mysub-service
  namespace: kros235-lifesub-ns
  labels:
    app: mysub
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: mysub
